
web: gunicorn Testapi.wsgi:application --log-file - --log-level debug
release: python manage.py makemigrations --noinput
release: python manage.py colectstatic --noinput

release: python manage.py migrate --noinput
